### ISSUE TITLE
Volume mounts issue in Windows

### ISSUE THREAD

**Issue by yellowcola** [katalon-studio-samples/ci-samples#2]
In case anyone running the sample code in windows: you need to add a slash in front of the directories in the docker command. Otherwise, docker can't find the folder to mount.

e.g.  
instead of "... docker run --rm -v "$project_dir":/katalon/katalon/source:ro ...", you need to add a slash before "$project_dir". Like "... docker run --rm -v "/$project_dir":/katalon/katalon/source:ro ...".

**Comment by minhhai2209** [comment]
Thank you for the tip. I'll check and fix this in the script.

**Comment by devalex88** [comment]
I've updated the sample script based on your suggestion. Thank you!
