### ISSUE TITLE
Why do i have to run as root?

### ISSUE THREAD

**Issue by O5ten** [katalon-studio-samples/ci-samples#23]
Hello, 

in the [example Jenkinsfile](https://github.com/katalon-studio-samples/ci-samples/blob/master/Jenkinsfile) it says that i have to run the container as the root user? Why is that? That means it will create any reports, logs and similar as the root user aswell meaning the Jenkins-user (who isn't root) will be unable to remove the workspaces that contains files it may not touch. 
```
    agent {
        docker {
            image 'katalonstudio/katalon'
            args "-u root"
        }
    }
```

**Comment by devalex88** [comment]
By default, Jenkins will map its user ID to the container, which prevents Katalon Studio and browsers to work properly. You can `chmod` any files created after the tests so that Jenkins will have enough access permissions.
