### ISSUE TITLE
Could not find .prj file in source folder

### ISSUE THREAD

**Issue by minhdoan159** [katalon-studio-samples/ci-samples#3]
I am running Katalon image using Docker for Windows.
I meet an issue that the projectfile could not be found in source folder so the katalon execution command failed:
C:\Users\minhdoan\kat-docker-examples\docker-images-samples (master -> origin)
λ bash .\katalon\run_chrome.sh
++ pwd
+ current_dir=/c/Users/minhdoan/kat-docker-examples/docker-images-samples
+++ dirname '.\katalon\run_chrome.sh'
++ cd '.\katalon'
++ pwd
+ project_dir=/c/Users/minhdoan/kat-docker-examples/docker-images-samples/katalon
+++ dirname '.\katalon\run_chrome.sh'
++ cd '.\katalon/..'
++ pwd
+ reports_dir=/c/Users/minhdoan/kat-docker-examples/docker-images-samples/reports/chrome
+ rm -rfv /c/Users/minhdoan/kat-docker-examples/docker-images-samples/reports/chrome
removed directory '/c/Users/minhdoan/kat-docker-examples/docker-images-samples/reports/chrome'
+ mkdir -p /c/Users/minhdoan/kat-docker-examples/docker-images-samples/reports/chrome
+ katalon_opts='-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="\Test Suites\TS_RegressionTest"'
+ docker run --rm -v //c/Users/minhdoan/kat-docker-examples/docker-images-samples/katalon:/katalon/katalon/source:ro -v /c/Users/minhdoan/kat-docker-examples/docker-images-samples/reports/chrome:/katalon/katalon/report -e 'KATALON_OPTS=-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="\Test Suites\TS_RegressionTest"' katalonstudio/katalon
Google Chrome 64.0.3282.186
Mozilla Firefox 58.0.2
Katalon Studio 5.3.1
Starting Katalon Studio
+ echo 'Starting Katalon Studio'
++ pwd
+ current_dir=/
+ tmp_dir=/katalon/katalon/tmp
+ mkdir -p /katalon/katalon/tmp
+ chmod -R 777 /katalon/katalon/tmp
+ project_dir=/katalon/katalon/project
+ mkdir -p /katalon/katalon/project
+ cp -r /katalon/katalon/source/. /katalon/katalon/project
+ touch /katalon/katalon/project/.classpath
+ chmod -R 777 /katalon/katalon/project
+ report_dir=/katalon/katalon/report
+ mkdir -p /katalon/katalon/report
+ chmod -R 777 /katalon/katalon/report
++ find /katalon/katalon/project -maxdepth 1 -type f -name '*.prj'
+ project_file=
+ cmd='/opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath= -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="\Test Suites\TS_RegressionTest"'
+ /katalon/base/scripts/xvfb.sh start
+ XVFB=/usr/bin/Xvfb
+ XVFBARGS=':99 -screen 0 1024x768x24 -fbdir /var/run -ac'
+ PIDFILE=/var/run/xvfb.pid
+ case "$1" in
+ echo -n 'Starting virtual X frame buffer :99 1024x768x24'
Starting virtual X frame buffer :99 1024x768x24+ start-stop-daemon --start --quiet --pidfile /var/run/xvfb.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -fbdir /var/run -ac
.
+ echo .
+ exit 0
+ cd /katalon/katalon/tmp
+ eval '/opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath= -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="\Test Suites\TS_RegressionTest"'
++ /opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath= -browserType=Chrome -retry=0 -statusDelay=15 '-testSuitePath=\Test Suites\TS_RegressionTest'
Invalid argument: Cannot find project '-browserType=Chrome'.

It seems the line of code did not works for me:
 `+ cp -r /katalon/katalon/source/. /katalon/katalon/project`
so the project file could not be found:
`find /katalon/katalon/project -maxdepth 1 -type f -name '*.prj'`

Please help to clarify it and any fix/work around on it!
Thanks!

**Comment by jejey** [comment]
hey, I have the exact same issue, I ran run_chrome.sh and run_firefox.sh and I get the same error : Invalid argument: Cannot find project '-browserType=Chrome'.
 (didn't forget to change the test suite name, and the script is in the root of katalon project)

Did you find a workaround ?

**Comment by jejey** [comment]
It was because there was a space in the path, ("My Program Files"), it's solved now

**Comment by MichalUrban999** [comment]
Hi guys, I try to run in the catalon test suite collection in windows 10 in docker, but I do not know the syntax structure. Would anyone be willing to help me run the test in the docker?

Here is we generate commnad from katalon:
katalon -noSplash -runMode = console -projectPath = "C: \ Users \ murban \ Katalon Studio \ AutomatTestCRM \ AutomatTestCRM_new.prj" -retry = 0 -testSuiteCollectionPath = "Test Suites / TestSuiteCollectionParallel / ParallelTest"


I have created in project folder: run_chrome.sh. What do I have to write into him?

I tried this, but it did not work :

docker run --rm -v //c/Users/murban/Katalon Studio\AutomatTestCRM/katalon:/katalon/katalon/source:ro -v /c/Users/murban/Katalon Studio\AutomatTestCRM/reports/chrome:/katalon/katalon/report -e 'KATALON_OPTS=-browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/TestSuiteCollectionParallel/ParallelTest"' katalonstudio/katalon

Thank you very much for your help.

**Comment by devalex88** [comment]
@MichalUrban999 We've simplified the syntax with more detailed sample scripts.
