### ISSUE TITLE
sample doesn't work

### ISSUE THREAD

**Issue by k4mus** [katalon-studio-samples/ci-samples#8]
Hi,
I'm trying to execute this example, but I got an error when run 
./katalon/run_chrome.sh
./katalon/run_firefox.sh
I got the same error.
could anybody help me?
( i'm using mac os)
`Request sent successfully.
Starting Groovy-Eclipse compiler resolver.  Specified compiler level: unspecified
133 2.4.7.xx-201611170128-e46 = ACTIVE
[Fatal Error] :1:1: Premature end of file.
[Fatal Error] :1:1: Premature end of file.
[Fatal Error] :1:1: Premature end of file.

--------------------------------------------------------------------------------
Test Suites/TS_RegressionTest - Firefox - 20180627_151445................0/2(0%)
--------------------------------------------------------------------------------

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/katalon/katalon/project/Libs/TempTestSuite1530112485582.groovy: 14: unable to resolve class internal.GlobalVariable
 @ line 14, column 1.
   import internal.GlobalVariable as GlobalVariable
   ^

1 error

Request sent successfully.

--------------------------------------------------------------------------------
Test Suites/TS_RegressionTest - Firefox - 20180627_151445................0/2(0%)
--------------------------------------------------------------------------------
`

**Comment by MickaelTH** [comment]
Same for me and same to be related to https://github.com/katalon-studio/docker-images/issues/12

**Comment by MickaelTH** [comment]
This is now resolved with latest version of katalon docker.
